languageCode = "en"
languageName = "English"
title = "Zenvila"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "https://zenvila.github.io/img/profile.jpg"

[author]
  name = "Haris Shahzad"
  image = "https://zenvila.github.io/img/profile.jpg"  # Fixed: Added slash
  headline = "Computer Science Student | System Programmer"
  bio = "Passionate about Automation, Robotics & Linux."

  # Social Links
  links = [
    { icon = "github", link = "https://github.com/zenvila" },
    { icon = "linkedin", link = "https://linkedin.com/in/haris-shahzad786" },
    { icon = "email", link = "mailto:arainharis151@gmail.com" }
  ]
