languageCode = "en"
languageName = "English"
title = "Zenvila"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  Logo = "images/penguin.svg"
  disableTextInHeader = true

[params.author]
  name = "Haris Shahzad"
  image = "https://zenvila.github.io/images/profile.jpg"
  headline = "System Programmer | Arch Linux Enthusiast"
  bio = "Obsessed with Linux, AI, and building things that actually work."
  links = [
    { github = "https://github.com/zenvila" },
    { linkedin = "https://linkedin.com/in/haris-shahzad786" },
    { email = "mailto:arainharis151@gmail.com" }
  ]
