languageCode = "en"
languageName = "English"
title = "Zenvila"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  Logo = "images/penguin.svg"
  disableTextInHeader = true

[params.author]
  name = "Haris Shahzad"
  image = "images/profile.jpg"
  headline = "Computer Science Student | System Programmer"
  bio = "Passionate about Automation, Robotics & Linux."
  links = [
    { github = "https://github.com/zenvila" },
    { linkedin = "https://linkedin.com/in/haris-shahzad786" },
    { email = "mailto:arainharis151@gmail.com" }
  ]
