[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 40

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 50

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 60

[[main]]
  name = "Authors"
  pageRef = "authors"
  weight = 70
