[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Resume"
  url = "/resume.pdf"  # We will upload the PDF later
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40
