colorScheme = "blowfish"
defaultTheme = "dark"

defaultBackgroundImage = "https://zenvila.github.io/background.jpg"
defaultFeaturedImage = "https://zenvila.github.io/background.jpg"
hotlinkFeatureImage = true

[homepage]
  layout = "background"
  homepageImage = "https://zenvila.github.io/background.jpg"
  showRecent = true     # <--- This adds the posts below your bio!
  showRecentItems = 6
  showMore = true
  cardView = true       # <--- Makes the posts look like nice cards

[header]
  layout = "fixed"

[footer]
  showPoweredBy = true

[article]
  showDate = true
  showAuthor = false
  showHero = true
  heroStyle = "background"
  showTaxonomies = true
  showReadingTime = true
  layoutBackgroundBlur = false
  layoutBackgroundHeaderSpace = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = false
  layoutBackgroundHeaderSpace = true
