colorScheme = "blowfish"
defaultTheme = "dark"

[homepage]
  layout = "background"
  showRecent = true     # <--- This adds the posts below your bio!
  showRecentItems = 4
  showMore = true
  cardView = true       # <--- Makes the posts look like nice cards

[header]
  layout = "fixed"

[footer]
  showPoweredBy = true

[article]
  showDate = true
  showAuthor = false
